@startuml Oasis

title Oasis Gantt Chart

Project starts the 18th of november 2021
[Team Interface] lasts 7 days and is colored in LightBlue

[Website Mockup] starts 2021-11-25 and lasts 7 days

[Customer Requirements Meeting] starts 2021-11-26
[Customer Requirements Meeting] lasts 1 day

[Role Elicitation] starts 2021-11-25 
[Cam, Kieron: Website, Gannt Chart, Requirements] starts at [Role Elicitation]'s end and lasts 14 days
[Will, Tabitha, Adam: Class UML Diagrams] starts at [Role Elicitation]'s end and lasts 14 days

@enduml